### ISSUE TITLE
Problems with compiling for python

### ISSUE THREAD

**Issue by GosiaTR** [benmaier/cMHRN#1]
Hello, I tried to setup your code for python and I run into some errors (examples listed)

Utilities.cpp (line 56): while ( (w>=v ) and (v<n) )
Utilities.cpp (line 104): if ( not already_visited[node] )
modified_small_world.cpp (line 202): if (distance <= max_neighbor or (N - distance) <= max_neighbor)

After fixing those pointed by my compiler it seems like cMHRN has been added as a module successfully, however "mhrn" is not recognized and mhrn_test.py fails to import it.

Do you have any ideas what can be the issue?
I work on a Windows machine and I also tried to compile your code for Matlab, again running into several syntax errors (different then those pointed out by python).

**Comment by benmaier** [comment]
Hi! `mhrn` is another one of my modules for generating MHRN, however I have not made it public yet. Nonetheless, `cMHRN` should work without it. Here's a code snippet that should work

```python
import cMHRN
import time


B = 10
L = 5
k = 6.0
xi = 0.3

N_meas = 10

t_c, k_c = 0.0, 0.0

seed = 1

for meas in range(N_meas):
    seed += 1

    tic = time.time()
    N, edges = cMHRN.fast_mhrn(B,L,k,xi,seed=seed)
    toc = time.time()
    t_c += (toc-tic) / N_meas
    k_c += len(edges)*2./B**L / N_meas

print("C++   : measured <k> = %4.2f, t = %fs" % (k_c,t_c))
```

Can you post the complete compiler output and errors for both compilations, Python and Matlab? It looks to me that those should be warnings because I compare size_t and long there.

Cheers

**Comment by GosiaTR** [comment]
The output of Python compilation is below. This is only the output of the first attempt at compilation. For some reasons my compiler doesn't like logic operators to be defined as words (actually I never seen that done in C++). When I changed them to standard logic operators:
and -> &&
not -> !
or -> ||
in all lines marked by the compiler (had to repeat compilation 4 times for the compiler to stop showing errors) compilation was successful. 

(base) d:\GOSIA_NETWORK_TOOLBOXES>pip install ./cMHRN_master
Processing d:\gosia_network_toolboxes\cmhrn_master
Requirement already satisfied: pybind11 in d:\gosia_anaconda\lib\site-packages (from cMHRN==0.1) (2.2.4)
Building wheels for collected packages: cMHRN
  Running setup.py bdist_wheel for cMHRN ... error
  Complete output from command d:\gosia_anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Gosia\\AppData\\Local\\Temp\\pip-req-build-6skfm75b\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Gosia\AppData\Local\Temp\pip-wheel-dtaizqut --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'cMHRN' extension
  creating build
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\cMHRN
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\gosia_anaconda\Include -IC:\Users\Gosia\AppData\Roaming\Python\Python36\Include -I./cMHRN/ -Id:\gosia_anaconda\include -Id:\gosia_anaconda\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /TpcMHRN/Utilities.cpp /Fobuild\temp.win-amd64-3.6\Release\cMHRN/Utilities.obj /EHsc
  Utilities.cpp
  cMHRN/Utilities.cpp(55): warning C4244: '=': conversion from 'double' to 'long', possible loss of data
  cMHRN/Utilities.cpp(56): error C2146: syntax error: missing ')' before identifier 'and'
  cMHRN/Utilities.cpp(56): error C3861: 'and': identifier not found
  cMHRN/Utilities.cpp(56): error C2059: syntax error: ')'
  cMHRN/Utilities.cpp(58): warning C4267: '=': conversion from 'size_t' to 'long', possible loss of data
  cMHRN/Utilities.cpp(58): error C2059: syntax error: ';'
  cMHRN/Utilities.cpp(70): error C2059: syntax error: '}'
  cMHRN/Utilities.cpp(70): error C2143: syntax error: missing ';' before '}'
  cMHRN/Utilities.cpp(78): error C2143: syntax error: missing ';' before '{'
  cMHRN/Utilities.cpp(78): error C2447: '{': missing function header (old-style formal list?)
  cMHRN/Utilities.cpp(104): error C2065: 'not': undeclared identifier
  cMHRN/Utilities.cpp(104): error C2146: syntax error: missing ')' before identifier 'already_visited'
  cMHRN/Utilities.cpp(104): error C2059: syntax error: ')'
  cMHRN/Utilities.cpp(106): error C2059: syntax error: ';'
  cMHRN/Utilities.cpp(111): error C2059: syntax error: 'return'
  cMHRN/Utilities.cpp(112): error C2059: syntax error: '}'
  cMHRN/Utilities.cpp(112): error C2143: syntax error: missing ';' before '}'
  cMHRN/Utilities.cpp(118): error C2143: syntax error: missing ';' before '{'
  cMHRN/Utilities.cpp(118): error C2447: '{': missing function header (old-style formal list?)
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for cMHRN
  Running setup.py clean for cMHRN
Failed to build cMHRN
Installing collected packages: cMHRN
  Running setup.py install for cMHRN ... error
    Complete output from command d:\gosia_anaconda\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Gosia\\AppData\\Local\\Temp\\pip-req-build-6skfm75b\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Gosia\AppData\Local\Temp\pip-record-0ral62zo\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'cMHRN' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\cMHRN
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\gosia_anaconda\Include -IC:\Users\Gosia\AppData\Roaming\Python\Python36\Include -I./cMHRN/ -Id:\gosia_anaconda\include -Id:\gosia_anaconda\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /TpcMHRN/Utilities.cpp /Fobuild\temp.win-amd64-3.6\Release\cMHRN/Utilities.obj /EHsc
    Utilities.cpp
    cMHRN/Utilities.cpp(55): warning C4244: '=': conversion from 'double' to 'long', possible loss of data
    cMHRN/Utilities.cpp(56): error C2146: syntax error: missing ')' before identifier 'and'
    cMHRN/Utilities.cpp(56): error C3861: 'and': identifier not found
    cMHRN/Utilities.cpp(56): error C2059: syntax error: ')'
    cMHRN/Utilities.cpp(58): warning C4267: '=': conversion from 'size_t' to 'long', possible loss of data
    cMHRN/Utilities.cpp(58): error C2059: syntax error: ';'
    cMHRN/Utilities.cpp(70): error C2059: syntax error: '}'
    cMHRN/Utilities.cpp(70): error C2143: syntax error: missing ';' before '}'
    cMHRN/Utilities.cpp(78): error C2143: syntax error: missing ';' before '{'
    cMHRN/Utilities.cpp(78): error C2447: '{': missing function header (old-style formal list?)
    cMHRN/Utilities.cpp(104): error C2065: 'not': undeclared identifier
    cMHRN/Utilities.cpp(104): error C2146: syntax error: missing ')' before identifier 'already_visited'
    cMHRN/Utilities.cpp(104): error C2059: syntax error: ')'
    cMHRN/Utilities.cpp(106): error C2059: syntax error: ';'
    cMHRN/Utilities.cpp(111): error C2059: syntax error: 'return'
    cMHRN/Utilities.cpp(112): error C2059: syntax error: '}'
    cMHRN/Utilities.cpp(112): error C2143: syntax error: missing ';' before '}'
    cMHRN/Utilities.cpp(118): error C2143: syntax error: missing ';' before '{'
    cMHRN/Utilities.cpp(118): error C2447: '{': missing function header (old-style formal list?)
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by benmaier** [comment]
Concerning the logical operators, this should be valid dialect ([wiki](https://en.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#Logical_operators) ).

Is it possible that you're using a compiler which is not familiar with the C++11-standard?

**Comment by benmaier** [comment]
Hi, according to [this thread on Stackoverflow](https://stackoverflow.com/questions/24414124/why-does-vs-not-define-the-alternative-tokens-for-logical-operators), the VS compiler just is not compliant to this standard by default, one has to `#include <iso646.h>` for the keywords to be recognizable. I fixed that in 6d5b65e, would you mind checking whether it works?

**Comment by GosiaTR** [comment]
Hello, I tried updated installer and it worked without issues (given that nothing was left from older installation: I removed earlier install with pip uninstall cMHRN, and then installed new version). My current compiler is VS2017.

**Comment by benmaier** [comment]
Cool! Can I close this issue then?
